<?php

namespace App\Notifications;

use App\Models\Interview;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class InterviewFeedbackReady extends Notification
{
    use Queueable;

    /** @var Interview */
    public $interview;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($interview)
    {
        $this->interview = $interview;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function via($notifiable)
    {
        return ['database', 'broadcast'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->line('The introduction to the notification.')
            ->action('Notification Action', url('/'))
            ->line('Thank you for using our application!');
    }

    /**
     * Get the array representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            'type'       => 'notification',
            //dynamic field what will be regenerated by the app and contains $this classname
            'title'      => $this->interview->vacancy->position,
            'text'       => __('Interview\'s members leaved their feedback'),
            'url'        => route('interviews.feedback.show', [$this->interview, 'read' => $this->id]),
            'icon'       => 'fas fa-brain',
            'color'      => 'success',
            'created_at' => now(),
            'read_at'    => null
        ];
    }
}
