<?php

namespace App\Notifications;

use App\Models\JobApplicant;
use App\Models\Quiz;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class QuizPassed extends Notification
{
    use Queueable;

    /**
     * @var Quiz $quiz
     */
    public $quiz;

    /**
     * @var JobApplicant $applicant
     */
    public $applicant;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($quiz, $applicant)
    {
        $this->quiz      = $quiz;
        $this->applicant = $applicant;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function via($notifiable)
    {
        return ['database', 'broadcast'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->line('The introduction to the notification.')
            ->action('Notification Action', url('/'))
            ->line('Thank you for using our application!');
    }

    /**
     * Get the array representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            'type'       => 'notification',
            //dynamic field what will be regenerated by the app and contains $this classname
            'title'      => $this->quiz->title,
            'text'       => __('A candidate passed the quiz'),
            'url'        => route('quizzes.reports.show.quizable', [$this->quiz, 'scope' => 'applicants', $this->applicant->id, 'read' => $this->id]),
            'icon'       => 'fas fa-cube',
            'color'      => 'success',
            'created_at' => now(),
            'read_at'    => null
        ];
    }
}
