<?php

namespace App\Notifications;

use App\Models\TimeOff;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class TimeOffApproved extends Notification
{
    use Queueable;

    /**
     * @var TimeOff $document
     */
    public $timeOff;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($timeOff)
    {
        $this->timeOff = $timeOff;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function via($notifiable)
    {
        return ['database', 'broadcast'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->line('The introduction to the notification.')
            ->action('Notification Action', url('/'))
            ->line('Thank you for using our application!');
    }

    /**
     * Get the array representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            'type'       => 'notification',
            //dynamic field what will be regenerated by the app and contains $this classname
            'title'      => TimeOff::$types[$this->timeOff->type],
            'text'       => __('Your time off is approved'),
            'url'        => route('time-offs.index', ['read' => $this->id]),
            'icon'       => 'fas fa-clock',
            'color'      => 'success',
            'created_at' => now(),
            'read_at'    => null
        ];
    }
}
