<?php

namespace App\Notifications;

use App\Models\Vacancy;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class VacancyPublished extends Notification
{
    use Queueable;

    /**
     * @var Vacancy $vacancy
     */
    public $vacancy;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($vacancy)
    {
        $this->vacancy = $vacancy;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function via($notifiable)
    {
        return ['database', 'broadcast'];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        return (new MailMessage)
            ->line('The introduction to the notification.')
            ->action('Notification Action', url('/'))
            ->line('Thank you for using our application!');
    }

    /**
     * Get the array representation of the notification.
     *
     * @param mixed $notifiable
     *
     * @return array
     */
    public function toArray($notifiable)
    {
        return [
            'type'       => 'notification',
            //dynamic field what will be regenerated by the app and contains $this classname
            'title'      => $this->vacancy->position,
            'text'       => __('A new vacancy was published'),
            'url'        => route('careers.show', [$this->vacancy, 'read' => $this->id]),
            'icon'       => 'fas fa-briefcase',
            'color'      => 'info',
            'created_at' => now(),
            'read_at'    => null
        ];
    }
}
